Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -5,7 +5,9 @@ on:
     branches:
       - main
      # - 'feature/*'
-
+  pull_request:
+    branches:
+      - develop
 #
 env:
   REGISTRY: ghcr.io
@@ -17,29 +19,29 @@ jobs:
       runs-on: ubuntu-latest
       steps:
       - uses: actions/checkout@v4
-      - uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: '17'
-          cache: 'maven'
+      # - uses: actions/setup-java@v4
+      #   with:
+      #     distribution: 'temurin'
+      #     java-version: '17'
+      #     cache: 'maven'
       - name: Build with and test
-        run:  mvn -B clean verify --file pom.xml  || true
-      - name: Upload Test Results
-        if: always() # Ensures the step runs even if tests fail
-        uses: actions/upload-artifact@v4
-        with:
-          name: test-results
-          path: target/surefire-reports/
-      - name: Count Failures and Decide
-        run: |
-          FAILURES=$(grep -oP 'failures="\K\d+' target/surefire-reports/*.xml | awk '{s+=$1} END {print s}')
-          echo "Total Failures: $FAILURES"
-          if [ "$FAILURES" -gt 2 ]; then
-              echo "Too many test failures ($FAILURES). Failing the pipeline."
-              exit 1
-          else
-              echo "Test failures within allowed limit ($FAILURES)."
-          fi
+        run:  echo "Hello World ${{ github.ref_name }} "
+      # - name: Upload Test Results
+      #   if: always() # Ensures the step runs even if tests fail
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: test-results
+      #     path: target/surefire-reports/
+      # - name: Count Failures and Decide
+      #   run: |
+      #     FAILURES=$(grep -oP 'failures="\K\d+' target/surefire-reports/*.xml | awk '{s+=$1} END {print s}')
+      #     echo "Total Failures: $FAILURES"
+      #     if [ "$FAILURES" -gt 2 ]; then
+      #         echo "Too many test failures ($FAILURES). Failing the pipeline."
+      #         exit 1
+      #     else
+      #         echo "Test failures within allowed limit ($FAILURES)."
+      #     fi
     # SAST-SonarCloud:
     #   runs-on: ubuntu-latest
     #   steps:
